sudo: required
services:
  - docker

  before_install:
    - docker build -t blackflame007/docker-react -f Dockerfile.dev .


script:
  - docker run blackflame007/docker-react npm run test -- --coverage
  