sudo: required
services:
  - docker

before_install:
  - docker build -t blackflame007/docker-react -f Dockerfile.dev .


script:
  # -- --coverage causes program to output then systematicly exit after run once
  - docker run blackflame007/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-1-866959873564"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"